version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "15672:15672"
      - "5672:5672"

  redisdata:
    image: redis:6.2.2-alpine
    ports:
      - "6379:6379"
  exchange.api:
    image: ${DOCKER_REGISTRY-}exchangeapi
    build:
      context: .
      dockerfile: src/Exchange.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development      
